### ISSUE TITLE
放到openwrt上报错，请问该怎么处理

### ISSUE THREAD

**Issue by yingyue2008** [sbwtw/haproxy-shadowsocks-checker#1]
放到openwrt上报错，请问该怎么处理
root@OpenWrt:~# haproxy -f /etc/haproxy.cfg
[ALERT] 044/004948 (10216) : Proxy 'shadowsocks-out' : 'option external-check' unable to find required 'global.external-check'.
[ALERT] 044/004948 (10216) : Fatal errors found in configuration.
其中haproxy.cfg配置文件的配置为
backend socks-out
    mode tcp
    option external-check
    external-check command "/root/haproxy-shadowsocks-checker.py"
    balance roundrobin
    server  6666    127.0.0.1:10801  check fall 5 rise 2 inter 7s
    server  6667    127.0.0.1:10802  check fall 5 rise 2 inter 7s
    server  6668    127.0.0.1:10803  check fall 5 rise 2 inter 7s

python版本已经指定为3，直接运行情况如下
root@OpenWrt:~# ./haproxy-shadowsocks-checker.py 
Traceback (most recent call last):
  File "./haproxy-shadowsocks-checker.py", line 82, in <module>
    host = sys.argv[3];
IndexError: list index out of range

**Comment by sbwtw** [comment]
global 节中加入 external-check 选项

Haproxy 调用 checker 时会传 4 个参数，前两个没用，后两个是 socks 地址，端口

具体的查下文档吧，现在没开电脑不方便

**Comment by yingyue2008** [comment]
感谢回复，在global 节中加入 external-check 选项后，第一个问题已解决。不过加入到haproxy后，所有节点都是down的，实际这些节点都是可以通的，我先再研究下吧

**Comment by sbwtw** [comment]
@yingyue2008 想要用 checker.py 测试的话，可以这样：
```bash
checker.py "" "" 127.0.0.1 8001
```
即第三个参数传 socks 主机名，第四个参数传端口，前两个参数传空。另外要确保你的 ss 服务器能访问 google

**Comment by yingyue2008** [comment]
最后确定是python版本问题，使用python3.6不行，报错ssl模块没有tls1.2，使用python3.7.6正常了。谢谢

**Comment by sbwtw** [comment]
在 README.md 中加了 `external-check` 的提示
