### ISSUE TITLE
建议在使用说明里提供补充

### ISSUE THREAD

**Issue by TrickLin** [sbwtw/haproxy-shadowsocks-checker#2]
首先是 我用的Debian10 haproxy版本1.8.19 这个版本已经需要在global 中启用 external-check
第二个是 如果使用这个脚本 一定要注释掉 默认配置文件里的chroot /var/lib/haproxy 这一行
调试了好久最终发现是这里的问题

**Comment by sbwtw** [comment]
`external-check` 在 Usage 中已经有描述了，不知道你说的是不是 `insecure-fork-wanted` 这个选项。不过我已经在 readme 中增加了相关内容了

**Comment by TrickLin** [comment]
啊...其实我主要想说的是
一定要注释掉默认配置文件中的 chroot
至少debian官方repo里的haproxy是有这一行的 我查了好久才找到无法使用的原因

**Comment by sbwtw** [comment]
@TrickLin chroot 的内容我也加上了
